pipeline {
    agent any
    environment { 
                AWS_Cred = credentials('night12pm')
            }
    parameters {
        string(defaultValue: "0", description: 'Only Tenant Number', name: 'tenant_number')
        choice(choices: ['dev','qa','int','tst','dem'], description: 'Choose the right environment', name: 'dev-tst-dem-int')
    }
    
    stages {
        stage('Git') {
            steps {
          git branch: 'dev-iam',
          credentialsId: 'jenkins-git-key',
          url: 'git@git.mckinsey-solutions.com:mash-periscope/ppv-tenant-iam-roles.git'
        }
        } 
        stage('TF Plan') {
            steps {
           sh 'terraform init'
           sh "terraform plan -out=plan.out \
           -var env=${params.dev-tst-dem-int} \
           -var tenant_id=${params.tenant_number}
           }
           }
           }
}           